# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lishizheng/Desktop/Code/langchain-impl-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lishizheng/Desktop/Code/langchain-impl-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lishizheng/Desktop/Code/langchain-impl-cpp/CMakeFiles /Users/lishizheng/Desktop/Code/langchain-impl-cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lishizheng/Desktop/Code/langchain-impl-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named langchain_cpp

# Build rule for target.
langchain_cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 langchain_cpp
.PHONY : langchain_cpp

# fast build rule for target.
langchain_cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/build
.PHONY : langchain_cpp/fast

#=============================================================================
# Target rules for targets named Catch2

# Build rule for target.
Catch2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2
.PHONY : Catch2

# fast build rule for target.
Catch2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2.dir/build
.PHONY : Catch2/fast

#=============================================================================
# Target rules for targets named Catch2WithMain

# Build rule for target.
Catch2WithMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2WithMain
.PHONY : Catch2WithMain

# fast build rule for target.
Catch2WithMain/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build
.PHONY : Catch2WithMain/fast

#=============================================================================
# Target rules for targets named unit_tests

# Build rule for target.
unit_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit_tests
.PHONY : unit_tests

# fast build rule for target.
unit_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/unit_tests.dir/build.make tests/CMakeFiles/unit_tests.dir/build
.PHONY : unit_tests/fast

src/chains/llm_chain.o: src/chains/llm_chain.cpp.o
.PHONY : src/chains/llm_chain.o

# target to build an object file
src/chains/llm_chain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/chains/llm_chain.cpp.o
.PHONY : src/chains/llm_chain.cpp.o

src/chains/llm_chain.i: src/chains/llm_chain.cpp.i
.PHONY : src/chains/llm_chain.i

# target to preprocess a source file
src/chains/llm_chain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/chains/llm_chain.cpp.i
.PHONY : src/chains/llm_chain.cpp.i

src/chains/llm_chain.s: src/chains/llm_chain.cpp.s
.PHONY : src/chains/llm_chain.s

# target to generate assembly for a file
src/chains/llm_chain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/chains/llm_chain.cpp.s
.PHONY : src/chains/llm_chain.cpp.s

src/chains/sequential_chain.o: src/chains/sequential_chain.cpp.o
.PHONY : src/chains/sequential_chain.o

# target to build an object file
src/chains/sequential_chain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/chains/sequential_chain.cpp.o
.PHONY : src/chains/sequential_chain.cpp.o

src/chains/sequential_chain.i: src/chains/sequential_chain.cpp.i
.PHONY : src/chains/sequential_chain.i

# target to preprocess a source file
src/chains/sequential_chain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/chains/sequential_chain.cpp.i
.PHONY : src/chains/sequential_chain.cpp.i

src/chains/sequential_chain.s: src/chains/sequential_chain.cpp.s
.PHONY : src/chains/sequential_chain.s

# target to generate assembly for a file
src/chains/sequential_chain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/chains/sequential_chain.cpp.s
.PHONY : src/chains/sequential_chain.cpp.s

src/core/config.o: src/core/config.cpp.o
.PHONY : src/core/config.o

# target to build an object file
src/core/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/core/config.cpp.o
.PHONY : src/core/config.cpp.o

src/core/config.i: src/core/config.cpp.i
.PHONY : src/core/config.i

# target to preprocess a source file
src/core/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/core/config.cpp.i
.PHONY : src/core/config.cpp.i

src/core/config.s: src/core/config.cpp.s
.PHONY : src/core/config.s

# target to generate assembly for a file
src/core/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/core/config.cpp.s
.PHONY : src/core/config.cpp.s

src/core/types.o: src/core/types.cpp.o
.PHONY : src/core/types.o

# target to build an object file
src/core/types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/core/types.cpp.o
.PHONY : src/core/types.cpp.o

src/core/types.i: src/core/types.cpp.i
.PHONY : src/core/types.i

# target to preprocess a source file
src/core/types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/core/types.cpp.i
.PHONY : src/core/types.cpp.i

src/core/types.s: src/core/types.cpp.s
.PHONY : src/core/types.s

# target to generate assembly for a file
src/core/types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/core/types.cpp.s
.PHONY : src/core/types.cpp.s

src/llm/base_llm.o: src/llm/base_llm.cpp.o
.PHONY : src/llm/base_llm.o

# target to build an object file
src/llm/base_llm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/llm/base_llm.cpp.o
.PHONY : src/llm/base_llm.cpp.o

src/llm/base_llm.i: src/llm/base_llm.cpp.i
.PHONY : src/llm/base_llm.i

# target to preprocess a source file
src/llm/base_llm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/llm/base_llm.cpp.i
.PHONY : src/llm/base_llm.cpp.i

src/llm/base_llm.s: src/llm/base_llm.cpp.s
.PHONY : src/llm/base_llm.s

# target to generate assembly for a file
src/llm/base_llm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/llm/base_llm.cpp.s
.PHONY : src/llm/base_llm.cpp.s

src/llm/openai_llm.o: src/llm/openai_llm.cpp.o
.PHONY : src/llm/openai_llm.o

# target to build an object file
src/llm/openai_llm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/llm/openai_llm.cpp.o
.PHONY : src/llm/openai_llm.cpp.o

src/llm/openai_llm.i: src/llm/openai_llm.cpp.i
.PHONY : src/llm/openai_llm.i

# target to preprocess a source file
src/llm/openai_llm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/llm/openai_llm.cpp.i
.PHONY : src/llm/openai_llm.cpp.i

src/llm/openai_llm.s: src/llm/openai_llm.cpp.s
.PHONY : src/llm/openai_llm.s

# target to generate assembly for a file
src/llm/openai_llm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/llm/openai_llm.cpp.s
.PHONY : src/llm/openai_llm.cpp.s

src/memory/memory.o: src/memory/memory.cpp.o
.PHONY : src/memory/memory.o

# target to build an object file
src/memory/memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/memory/memory.cpp.o
.PHONY : src/memory/memory.cpp.o

src/memory/memory.i: src/memory/memory.cpp.i
.PHONY : src/memory/memory.i

# target to preprocess a source file
src/memory/memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/memory/memory.cpp.i
.PHONY : src/memory/memory.cpp.i

src/memory/memory.s: src/memory/memory.cpp.s
.PHONY : src/memory/memory.s

# target to generate assembly for a file
src/memory/memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/memory/memory.cpp.s
.PHONY : src/memory/memory.cpp.s

src/metrics/metrics.o: src/metrics/metrics.cpp.o
.PHONY : src/metrics/metrics.o

# target to build an object file
src/metrics/metrics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/metrics/metrics.cpp.o
.PHONY : src/metrics/metrics.cpp.o

src/metrics/metrics.i: src/metrics/metrics.cpp.i
.PHONY : src/metrics/metrics.i

# target to preprocess a source file
src/metrics/metrics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/metrics/metrics.cpp.i
.PHONY : src/metrics/metrics.cpp.i

src/metrics/metrics.s: src/metrics/metrics.cpp.s
.PHONY : src/metrics/metrics.s

# target to generate assembly for a file
src/metrics/metrics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/metrics/metrics.cpp.s
.PHONY : src/metrics/metrics.cpp.s

src/prompts/prompt_template.o: src/prompts/prompt_template.cpp.o
.PHONY : src/prompts/prompt_template.o

# target to build an object file
src/prompts/prompt_template.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/prompts/prompt_template.cpp.o
.PHONY : src/prompts/prompt_template.cpp.o

src/prompts/prompt_template.i: src/prompts/prompt_template.cpp.i
.PHONY : src/prompts/prompt_template.i

# target to preprocess a source file
src/prompts/prompt_template.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/prompts/prompt_template.cpp.i
.PHONY : src/prompts/prompt_template.cpp.i

src/prompts/prompt_template.s: src/prompts/prompt_template.cpp.s
.PHONY : src/prompts/prompt_template.s

# target to generate assembly for a file
src/prompts/prompt_template.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/prompts/prompt_template.cpp.s
.PHONY : src/prompts/prompt_template.cpp.s

src/retrievers/bm25_retriever.o: src/retrievers/bm25_retriever.cpp.o
.PHONY : src/retrievers/bm25_retriever.o

# target to build an object file
src/retrievers/bm25_retriever.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/retrievers/bm25_retriever.cpp.o
.PHONY : src/retrievers/bm25_retriever.cpp.o

src/retrievers/bm25_retriever.i: src/retrievers/bm25_retriever.cpp.i
.PHONY : src/retrievers/bm25_retriever.i

# target to preprocess a source file
src/retrievers/bm25_retriever.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/retrievers/bm25_retriever.cpp.i
.PHONY : src/retrievers/bm25_retriever.cpp.i

src/retrievers/bm25_retriever.s: src/retrievers/bm25_retriever.cpp.s
.PHONY : src/retrievers/bm25_retriever.s

# target to generate assembly for a file
src/retrievers/bm25_retriever.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/retrievers/bm25_retriever.cpp.s
.PHONY : src/retrievers/bm25_retriever.cpp.s

src/retrievers/hybrid_retriever.o: src/retrievers/hybrid_retriever.cpp.o
.PHONY : src/retrievers/hybrid_retriever.o

# target to build an object file
src/retrievers/hybrid_retriever.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/retrievers/hybrid_retriever.cpp.o
.PHONY : src/retrievers/hybrid_retriever.cpp.o

src/retrievers/hybrid_retriever.i: src/retrievers/hybrid_retriever.cpp.i
.PHONY : src/retrievers/hybrid_retriever.i

# target to preprocess a source file
src/retrievers/hybrid_retriever.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/retrievers/hybrid_retriever.cpp.i
.PHONY : src/retrievers/hybrid_retriever.cpp.i

src/retrievers/hybrid_retriever.s: src/retrievers/hybrid_retriever.cpp.s
.PHONY : src/retrievers/hybrid_retriever.s

# target to generate assembly for a file
src/retrievers/hybrid_retriever.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/retrievers/hybrid_retriever.cpp.s
.PHONY : src/retrievers/hybrid_retriever.cpp.s

src/retrievers/inverted_index_retriever.o: src/retrievers/inverted_index_retriever.cpp.o
.PHONY : src/retrievers/inverted_index_retriever.o

# target to build an object file
src/retrievers/inverted_index_retriever.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/retrievers/inverted_index_retriever.cpp.o
.PHONY : src/retrievers/inverted_index_retriever.cpp.o

src/retrievers/inverted_index_retriever.i: src/retrievers/inverted_index_retriever.cpp.i
.PHONY : src/retrievers/inverted_index_retriever.i

# target to preprocess a source file
src/retrievers/inverted_index_retriever.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/retrievers/inverted_index_retriever.cpp.i
.PHONY : src/retrievers/inverted_index_retriever.cpp.i

src/retrievers/inverted_index_retriever.s: src/retrievers/inverted_index_retriever.cpp.s
.PHONY : src/retrievers/inverted_index_retriever.s

# target to generate assembly for a file
src/retrievers/inverted_index_retriever.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/retrievers/inverted_index_retriever.cpp.s
.PHONY : src/retrievers/inverted_index_retriever.cpp.s

src/text/text_processor.o: src/text/text_processor.cpp.o
.PHONY : src/text/text_processor.o

# target to build an object file
src/text/text_processor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/text/text_processor.cpp.o
.PHONY : src/text/text_processor.cpp.o

src/text/text_processor.i: src/text/text_processor.cpp.i
.PHONY : src/text/text_processor.i

# target to preprocess a source file
src/text/text_processor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/text/text_processor.cpp.i
.PHONY : src/text/text_processor.cpp.i

src/text/text_processor.s: src/text/text_processor.cpp.s
.PHONY : src/text/text_processor.s

# target to generate assembly for a file
src/text/text_processor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/text/text_processor.cpp.s
.PHONY : src/text/text_processor.cpp.s

src/utils/logging.o: src/utils/logging.cpp.o
.PHONY : src/utils/logging.o

# target to build an object file
src/utils/logging.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/utils/logging.cpp.o
.PHONY : src/utils/logging.cpp.o

src/utils/logging.i: src/utils/logging.cpp.i
.PHONY : src/utils/logging.i

# target to preprocess a source file
src/utils/logging.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/utils/logging.cpp.i
.PHONY : src/utils/logging.cpp.i

src/utils/logging.s: src/utils/logging.cpp.s
.PHONY : src/utils/logging.s

# target to generate assembly for a file
src/utils/logging.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/utils/logging.cpp.s
.PHONY : src/utils/logging.cpp.s

src/utils/memory_pool.o: src/utils/memory_pool.cpp.o
.PHONY : src/utils/memory_pool.o

# target to build an object file
src/utils/memory_pool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/utils/memory_pool.cpp.o
.PHONY : src/utils/memory_pool.cpp.o

src/utils/memory_pool.i: src/utils/memory_pool.cpp.i
.PHONY : src/utils/memory_pool.i

# target to preprocess a source file
src/utils/memory_pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/utils/memory_pool.cpp.i
.PHONY : src/utils/memory_pool.cpp.i

src/utils/memory_pool.s: src/utils/memory_pool.cpp.s
.PHONY : src/utils/memory_pool.s

# target to generate assembly for a file
src/utils/memory_pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/utils/memory_pool.cpp.s
.PHONY : src/utils/memory_pool.cpp.s

src/utils/simd_ops.o: src/utils/simd_ops.cpp.o
.PHONY : src/utils/simd_ops.o

# target to build an object file
src/utils/simd_ops.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/utils/simd_ops.cpp.o
.PHONY : src/utils/simd_ops.cpp.o

src/utils/simd_ops.i: src/utils/simd_ops.cpp.i
.PHONY : src/utils/simd_ops.i

# target to preprocess a source file
src/utils/simd_ops.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/utils/simd_ops.cpp.i
.PHONY : src/utils/simd_ops.cpp.i

src/utils/simd_ops.s: src/utils/simd_ops.cpp.s
.PHONY : src/utils/simd_ops.s

# target to generate assembly for a file
src/utils/simd_ops.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/utils/simd_ops.cpp.s
.PHONY : src/utils/simd_ops.cpp.s

src/utils/thread_pool.o: src/utils/thread_pool.cpp.o
.PHONY : src/utils/thread_pool.o

# target to build an object file
src/utils/thread_pool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/utils/thread_pool.cpp.o
.PHONY : src/utils/thread_pool.cpp.o

src/utils/thread_pool.i: src/utils/thread_pool.cpp.i
.PHONY : src/utils/thread_pool.i

# target to preprocess a source file
src/utils/thread_pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/utils/thread_pool.cpp.i
.PHONY : src/utils/thread_pool.cpp.i

src/utils/thread_pool.s: src/utils/thread_pool.cpp.s
.PHONY : src/utils/thread_pool.s

# target to generate assembly for a file
src/utils/thread_pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/utils/thread_pool.cpp.s
.PHONY : src/utils/thread_pool.cpp.s

src/vectorstores/simple_vector_store.o: src/vectorstores/simple_vector_store.cpp.o
.PHONY : src/vectorstores/simple_vector_store.o

# target to build an object file
src/vectorstores/simple_vector_store.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/vectorstores/simple_vector_store.cpp.o
.PHONY : src/vectorstores/simple_vector_store.cpp.o

src/vectorstores/simple_vector_store.i: src/vectorstores/simple_vector_store.cpp.i
.PHONY : src/vectorstores/simple_vector_store.i

# target to preprocess a source file
src/vectorstores/simple_vector_store.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/vectorstores/simple_vector_store.cpp.i
.PHONY : src/vectorstores/simple_vector_store.cpp.i

src/vectorstores/simple_vector_store.s: src/vectorstores/simple_vector_store.cpp.s
.PHONY : src/vectorstores/simple_vector_store.s

# target to generate assembly for a file
src/vectorstores/simple_vector_store.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/langchain_cpp.dir/build.make CMakeFiles/langchain_cpp.dir/src/vectorstores/simple_vector_store.cpp.s
.PHONY : src/vectorstores/simple_vector_store.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Catch2"
	@echo "... Catch2WithMain"
	@echo "... langchain_cpp"
	@echo "... unit_tests"
	@echo "... src/chains/llm_chain.o"
	@echo "... src/chains/llm_chain.i"
	@echo "... src/chains/llm_chain.s"
	@echo "... src/chains/sequential_chain.o"
	@echo "... src/chains/sequential_chain.i"
	@echo "... src/chains/sequential_chain.s"
	@echo "... src/core/config.o"
	@echo "... src/core/config.i"
	@echo "... src/core/config.s"
	@echo "... src/core/types.o"
	@echo "... src/core/types.i"
	@echo "... src/core/types.s"
	@echo "... src/llm/base_llm.o"
	@echo "... src/llm/base_llm.i"
	@echo "... src/llm/base_llm.s"
	@echo "... src/llm/openai_llm.o"
	@echo "... src/llm/openai_llm.i"
	@echo "... src/llm/openai_llm.s"
	@echo "... src/memory/memory.o"
	@echo "... src/memory/memory.i"
	@echo "... src/memory/memory.s"
	@echo "... src/metrics/metrics.o"
	@echo "... src/metrics/metrics.i"
	@echo "... src/metrics/metrics.s"
	@echo "... src/prompts/prompt_template.o"
	@echo "... src/prompts/prompt_template.i"
	@echo "... src/prompts/prompt_template.s"
	@echo "... src/retrievers/bm25_retriever.o"
	@echo "... src/retrievers/bm25_retriever.i"
	@echo "... src/retrievers/bm25_retriever.s"
	@echo "... src/retrievers/hybrid_retriever.o"
	@echo "... src/retrievers/hybrid_retriever.i"
	@echo "... src/retrievers/hybrid_retriever.s"
	@echo "... src/retrievers/inverted_index_retriever.o"
	@echo "... src/retrievers/inverted_index_retriever.i"
	@echo "... src/retrievers/inverted_index_retriever.s"
	@echo "... src/text/text_processor.o"
	@echo "... src/text/text_processor.i"
	@echo "... src/text/text_processor.s"
	@echo "... src/utils/logging.o"
	@echo "... src/utils/logging.i"
	@echo "... src/utils/logging.s"
	@echo "... src/utils/memory_pool.o"
	@echo "... src/utils/memory_pool.i"
	@echo "... src/utils/memory_pool.s"
	@echo "... src/utils/simd_ops.o"
	@echo "... src/utils/simd_ops.i"
	@echo "... src/utils/simd_ops.s"
	@echo "... src/utils/thread_pool.o"
	@echo "... src/utils/thread_pool.i"
	@echo "... src/utils/thread_pool.s"
	@echo "... src/vectorstores/simple_vector_store.o"
	@echo "... src/vectorstores/simple_vector_store.i"
	@echo "... src/vectorstores/simple_vector_store.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

